set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]

set_property PACKAGE_PIN B4 [get_ports {left_seg_pins[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {left_seg_pins[0]}]
set_property SLEW SLOW [get_ports {left_seg_pins[0]}]
set_property PACKAGE_PIN A4 [get_ports {left_seg_pins[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {left_seg_pins[1]}]
set_property PACKAGE_PIN A3 [get_ports {left_seg_pins[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {left_seg_pins[2]}]
set_property PACKAGE_PIN B1 [get_ports {left_seg_pins[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {left_seg_pins[3]}]
set_property PACKAGE_PIN A1 [get_ports {left_seg_pins[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {left_seg_pins[4]}]
set_property PACKAGE_PIN B3 [get_ports {left_seg_pins[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {left_seg_pins[5]}]
set_property PACKAGE_PIN B2 [get_ports {left_seg_pins[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {left_seg_pins[6]}]

set_property IOSTANDARD LVCMOS33 [get_ports left_p_pin]
set_property PACKAGE_PIN D5 [get_ports left_p_pin]

set_property PACKAGE_PIN H1 [get_ports {left_gnd_pins[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {left_gnd_pins[0]}]
set_property PACKAGE_PIN C1 [get_ports {left_gnd_pins[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {left_gnd_pins[1]}]
set_property PACKAGE_PIN C2 [get_ports {left_gnd_pins[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {left_gnd_pins[2]}]
set_property PACKAGE_PIN G2 [get_ports {left_gnd_pins[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {left_gnd_pins[3]}]
# Clock input (100MHz)
set_property IOSTANDARD LVCMOS33 [get_ports clk_in]
set_property PACKAGE_PIN P17 [get_ports clk_in]

# Right 7-segment display - Segment pins (a-g)
set_property PACKAGE_PIN D4 [get_ports {right_seg_pins[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {right_seg_pins[0]}]
set_property PACKAGE_PIN E3 [get_ports {right_seg_pins[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {right_seg_pins[1]}]
set_property PACKAGE_PIN D3 [get_ports {right_seg_pins[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {right_seg_pins[2]}]
set_property PACKAGE_PIN F4 [get_ports {right_seg_pins[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {right_seg_pins[3]}]
set_property PACKAGE_PIN F3 [get_ports {right_seg_pins[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {right_seg_pins[4]}]
set_property PACKAGE_PIN E2 [get_ports {right_seg_pins[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {right_seg_pins[5]}]
set_property PACKAGE_PIN D2 [get_ports {right_seg_pins[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {right_seg_pins[6]}]

set_property PACKAGE_PIN G6 [get_ports {right_gnd_pins[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {right_gnd_pins[0]}]
set_property PACKAGE_PIN E1 [get_ports {right_gnd_pins[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {right_gnd_pins[1]}]
set_property PACKAGE_PIN F1 [get_ports {right_gnd_pins[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {right_gnd_pins[2]}]
set_property PACKAGE_PIN G1 [get_ports {right_gnd_pins[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {right_gnd_pins[3]}]

set_property PACKAGE_PIN H2 [get_ports right_p_pin]
set_property IOSTANDARD LVCMOS33 [get_ports right_p_pin]

set_property PACKAGE_PIN R1 [get_ports {left_switch_pins[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {left_switch_pins[0]}]
set_property PACKAGE_PIN N4 [get_ports {left_switch_pins[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {left_switch_pins[1]}]
set_property PACKAGE_PIN M4 [get_ports {left_switch_pins[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {left_switch_pins[2]}]
set_property PACKAGE_PIN R2 [get_ports {left_switch_pins[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {left_switch_pins[3]}]
set_property PACKAGE_PIN P2 [get_ports {left_switch_pins[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {left_switch_pins[4]}]
set_property PACKAGE_PIN P3 [get_ports {left_switch_pins[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {left_switch_pins[5]}]
set_property PACKAGE_PIN P4 [get_ports {left_switch_pins[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {left_switch_pins[6]}]
set_property PACKAGE_PIN P5 [get_ports {left_switch_pins[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {left_switch_pins[7]}]

set_property PACKAGE_PIN T5 [get_ports {right_switch_pins[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {right_switch_pins[0]}]
set_property PACKAGE_PIN T3 [get_ports {right_switch_pins[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {right_switch_pins[1]}]
set_property PACKAGE_PIN R3 [get_ports {right_switch_pins[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {right_switch_pins[2]}]
set_property PACKAGE_PIN V4 [get_ports {right_switch_pins[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {right_switch_pins[3]}]
set_property PACKAGE_PIN V5 [get_ports {right_switch_pins[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {right_switch_pins[4]}]
set_property PACKAGE_PIN V2 [get_ports {right_switch_pins[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {right_switch_pins[5]}]
set_property PACKAGE_PIN U2 [get_ports {right_switch_pins[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {right_switch_pins[6]}]
set_property PACKAGE_PIN U3 [get_ports {right_switch_pins[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {right_switch_pins[7]}]

set_property IOSTANDARD LVCMOS33 [get_ports {da_input_pin[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_input_pin[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_input_pin[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_input_pin[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_input_pin[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_input_pin[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_input_pin[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_input_pin[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_input_pin[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_input_pin[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_input_pin[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_input_pin[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_input_pin[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_input_pin[0]}]
set_property PACKAGE_PIN B11 [get_ports {da_input_pin[0]}]
set_property PACKAGE_PIN C14 [get_ports {da_input_pin[1]}]
set_property PACKAGE_PIN D14 [get_ports {da_input_pin[2]}]
set_property PACKAGE_PIN B14 [get_ports {da_input_pin[3]}]
set_property PACKAGE_PIN B13 [get_ports {da_input_pin[4]}]
set_property PACKAGE_PIN F14 [get_ports {da_input_pin[5]}]
set_property PACKAGE_PIN F13 [get_ports {da_input_pin[6]}]
set_property PACKAGE_PIN A18 [get_ports {da_input_pin[7]}]
set_property PACKAGE_PIN B18 [get_ports {da_input_pin[8]}]
set_property PACKAGE_PIN A14 [get_ports {da_input_pin[9]}]
set_property PACKAGE_PIN A13 [get_ports {da_input_pin[10]}]
set_property PACKAGE_PIN A16 [get_ports {da_input_pin[11]}]
set_property PACKAGE_PIN A15 [get_ports {da_input_pin[12]}]
set_property PACKAGE_PIN B17 [get_ports {da_input_pin[13]}]

set_property PACKAGE_PIN J2 [get_ports led2_pin]
set_property PACKAGE_PIN J3 [get_ports led3_pin]
set_property IOSTANDARD LVCMOS33 [get_ports led2_pin]
set_property IOSTANDARD LVCMOS33 [get_ports led3_pin]

set_property PACKAGE_PIN B16 [get_ports da_clk]
set_property IOSTANDARD LVCMOS33 [get_ports da_clk]

set_property IOSTANDARD LVCMOS33 [get_ports {ad_input_pin[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_input_pin[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_input_pin[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_input_pin[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_input_pin[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_input_pin[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_input_pin[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_input_pin[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_input_pin[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_input_pin[0]}]
set_property PACKAGE_PIN G17 [get_ports {ad_input_pin[9]}]
set_property PACKAGE_PIN K13 [get_ports {ad_input_pin[8]}]
set_property PACKAGE_PIN J13 [get_ports {ad_input_pin[7]}]
set_property PACKAGE_PIN E17 [get_ports {ad_input_pin[6]}]
set_property PACKAGE_PIN D17 [get_ports {ad_input_pin[5]}]
set_property PACKAGE_PIN H14 [get_ports {ad_input_pin[4]}]
set_property PACKAGE_PIN G14 [get_ports {ad_input_pin[3]}]
set_property PACKAGE_PIN F15 [get_ports {ad_input_pin[2]}]
set_property PACKAGE_PIN F16 [get_ports {ad_input_pin[1]}]
set_property PACKAGE_PIN H16 [get_ports {ad_input_pin[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports ad_clk]
set_property PACKAGE_PIN H17 [get_ports ad_clk]

set_property PACKAGE_PIN R11 [get_ports {keys[0]}]
set_property PACKAGE_PIN V1 [get_ports {keys[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {keys[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {keys[0]}]

set_property PULLDOWN true [get_ports {ad_input_pin[9]}]
set_property PULLDOWN true [get_ports {ad_input_pin[8]}]
set_property PULLDOWN true [get_ports {ad_input_pin[7]}]
set_property PULLDOWN true [get_ports {ad_input_pin[6]}]
set_property PULLDOWN true [get_ports {ad_input_pin[5]}]
set_property PULLDOWN true [get_ports {ad_input_pin[4]}]
set_property PULLDOWN true [get_ports {ad_input_pin[3]}]
set_property PULLDOWN true [get_ports {ad_input_pin[2]}]
set_property PULLDOWN true [get_ports {ad_input_pin[1]}]
set_property PULLDOWN true [get_ports {ad_input_pin[0]}]

set_property PACKAGE_PIN R15 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
